export const COMMUNES: Record<string, string[]> = {
  "01": ["Adrar", "Reggane", "Timiaouine", "Aoulef", "Tsabit", "Fougarout", "Zaouiet Kounta", "Aougrout"],
  "02": ["Chlef", "Ténès", "Boukadir", "Oued Fodda", "Sendjas", "Ouled Ben Abdelkader", "El Karimia", "Taougrite"],
  "03": ["Laghouat", "Aflou", "Ain Madhi", "Gueltet Sidi Saad", "Brida", "El Ghicha", "Hassi R'Mel"],
  "04": ["Oum El Bouaghi", "Aïn Beïda", "Aïn M'lila", "F'kirina", "Ain Fakroun"],
  "05": ["Batna", "Arris", "Barika", "Merouana", "T'Kout", "Ain Touta", "N'Gaous", "Tazoult"],
  "06": ["Béjaïa", "Akbou", "Amizour", "Sidi Aïch", "Kherrata", "El Kseur", "Tazmalt"],
  "07": ["Biskra", "Tolga", "Ouled Djellal", "Sidi Okba", "El Kantara", "M'Chouneche"],
  "08": ["Béchar", "Abadla", "Kenadsa", "Béni Abbès", "Taghit", "Lahmar"],
  "09": ["Blida", "Boufarik", "Ouled Yaïch", "Beni Mered", "Chebli", "El Affroun", "Larbaa", "Meftah", "Mouzaïa", "Bougara"],
  "10": ["Bouira", "Lakhdaria", "Sour El Ghozlane", "Aïn Bessem", "M'Chedallah", "Bechloul"],
  "11": ["Tamanrasset", "In Salah", "In Ghar", "Abalessa", "In Amguel"],
  "12": ["Tébessa", "Bir El Ater", "Cheria", "Ouenza", "El Aouinet", "Negrine"],
  "13": ["Tlemcen", "Maghnia", "Ghazaouet", "Nedroma", "Sebdou", "Remchi", "Hennaya", "Bab El Assa"],
  "14": ["Tiaret", "Sougueur", "Frenda", "Mahdia", "Rahouia", "Dahmouni", "Ksar Chellala"],
  "15": ["Tizi Ouzou", "Azeffoun", "Azazga", "Larbâa Nath Irathen", "Draâ El Mizan", "Tigzirt", "Boghni", "Ain El Hammam"],
  "16": ["Alger Centre", "Sidi M'Hamed", "El Biar", "Kouba", "Bab El Oued", "Casbah", "Hydra", "Bir Mourad Raïs", "Birmandreis", "El Harrach", "Bab Ezzouar", "Dar El Beïda", "Reghaïa", "Rouïba", "Bordj El Kiffan", "Bordj El Bahri", "Zeralda", "Cheraga", "Dely Ibrahim", "Ouled Fayet", "Draria", "Douera", "Baba Hassen", "Les Eucalyptus", "Baraki", "Ain Taya"],
  "17": ["Djelfa", "Hassi Bahbah", "Messaad", "Ain Oussera", "Dar Chioukh", "Charef"],
  "18": ["Jijel", "Taher", "El Milia", "Chekfa", "Djimla", "El Aouana", "Ziama Mansouriah"],
  "19": ["Sétif", "El Eulma", "Bougaa", "Ain Oulmene", "Ain Arnat", "Salah Bey", "Djemila"],
  "20": ["Saïda", "Youb", "Sidi Boubekeur", "El Hassasna", "Ain El Hadjar"],
  "21": ["Skikda", "Collo", "El Harrouch", "Azzaba", "Tamalous", "Sidi Mezghiche"],
  "22": ["Sidi Bel Abbès", "Tessala", "Sfisef", "Ben Badis", "Mostefa Ben Brahim", "Telagh"],
  "23": ["Annaba", "El Bouni", "El Hadjar", "Seraïdi", "Berrahal", "Chetaïbi"],
  "24": ["Guelma", "Héliopolis", "Oued Zenati", "Bouchegouf", "Hammou Bouhadjar", "Ain Makhlouf"],
  "25": ["Constantine", "El Khroub", "Hamma Bouziane", "Didouche Mourad", "Zouaghi", "Ali Mendjeli"],
  "26": ["Médéa", "Ksar El Boukhari", "Berrouaghia", "Beni Slimane", "Tablat", "Ouzera"],
  "27": ["Mostaganem", "Aïn Nouïssy", "Bouguirat", "Aïn Tédelès", "Sidi Ali", "Mesra"],
  "28": ["M'Sila", "Bou Saâda", "Sidi Aïssa", "Maadid", "Ain El Hadjel", "M'Tarfa"],
  "29": ["Mascara", "Sig", "Mohammadia", "Ghriss", "Tighennif", "Oued Taria"],
  "30": ["Ouargla", "Hassi Messaoud", "Touggourt", "N'Goussa", "Temacine", "El Borma"],
  "31": ["Oran", "Bir El Djir", "Es Senia", "Arzew", "Gdyel", "Bethioua", "Ain El Turk", "Oued Tlelat", "Boutlelis"],
  "32": ["El Bayadh", "Rogassa", "Bougtob", "Brezina", "El Abiodh Sidi Cheikh"],
  "33": ["Illizi", "Djanet", "In Amenas", "Bordj Omar Driss"],
  "34": ["Bordj Bou Arréridj", "Ras El Oued", "Bordj Ghedir", "Mansoura", "El Achir"],
  "35": ["Boumerdès", "Dellys", "Bordj Menaïel", "Baghlia", "Khemis El Khechna", "Boudouaou", "Naciria"],
  "36": ["El Tarf", "El Kala", "Drean", "Besbes", "Ben M'Hidi"],
  "37": ["Tindouf", "Oum El Assel"],
  "38": ["Tissemsilt", "Theniet El Had", "Lardjem", "Ammari", "Khemisti"],
  "39": ["El Oued", "Guemar", "Robbah", "Bayadha", "Hassi Khalifa", "M'Ghair"],
  "40": ["Khenchela", "Chechar", "Kaïs", "Bouhmama", "Ouled Rechache"],
  "41": ["Souk Ahras", "M'Daourouch", "Sedrata", "Taoura", "Haddada"],
  "42": ["Tipaza", "Kolea", "Bou Ismail", "Cherchell", "Ahmer El Ain", "Gouraya", "Hadout"],
  "43": ["Mila", "Chelghoum Laïd", "Teleghma", "Ferdjioua", "Grarem Gouga", "Tadjenanet"],
  "44": ["Aïn Defla", "Miliana", "Khemis Miliana", "Hammam Righa", "El Attaf", "Djelida"],
  "45": ["Naâma", "Mécheria", "Aïn Séfra", "Moghrar", "Asla"],
  "46": ["Aïn Témouchent", "Hammam Bou Hadjar", "Beni Saf", "El Amria", "El Malah"],
  "47": ["Ghardaïa", "Metlili", "El Meniaa", "Bounoura", "El Guerrara", "Zelfana"],
  "48": ["Relizane", "Oued Rhiou", "Mazouna", "Ammi Moussa", "Yellel", "Zemmora"],
  "49": ["Timimoun", "Aougrout", "Charouine"],
  "50": ["Bordj Badji Mokhtar", "Timiaouine"],
  "51": ["Ouled Djellal", "Sidi Khaled"],
  "52": ["Béni Abbès", "Kerzaz", "Tabelbala"],
  "53": ["In Salah", "In Ghar"],
  "54": ["In Guezzam", "Tin Zaouatine"],
  "55": ["Touggourt", "Temacine", "Megarine"],
  "56": ["Djanet", "Bordj El Haouas"],
  "57": ["El M'Ghair", "Djamaa"],
  "58": ["El Meniaa", "Hassi Gara"]
};
